/**
 * hardcoded publisher allowlist. alerts signed by keys outside this list are dropped on fetch
 * with a console warning. v0 ships with a single placeholder pubkey for kitty4d (the chromatika
 * team's safety-alerts publisher); replace with the real one before public release.
 *
 * future: graduate to an on-chain `PublisherCap` registry on Sui where the chromatika team
 * holds the root cap and can add / revoke publishers. the wallet would poll the registry
 * alongside the alerts feed. for v0 the static allowlist is sufficient because we only have
 * one publisher.
 *
 * replacing the placeholder:
 *   1. generate a fresh ed25519 keypair: `node wallet-extension/scripts/publish-alert.mjs --gen-key`
 *   2. save the privkey somewhere safe (1password, hardware wallet, etc).
 *   3. paste the pubkey base64 here.
 *   4. bump `BUNDLED_PUBLISHERS_REVISION` so dev installs that cached the old value pull again
 *      after extension reload.
 */

export interface PublisherEntry {
  /** base64 ed25519 pubkey (32 bytes raw -> 44-char base64). */
  pubkeyB64: string;
  /** human label shown next to alerts (e.g. "kitty4d (chromatika team)"). */
  label: string;
  /** when this entry was added (ISO date). audit trail. */
  addedAt: string;
}

/**
 * bumped on every change to BUNDLED_PUBLISHERS. lets cached storage detect mismatches and
 * refetch / revalidate alerts when allowlist rotates.
 */
export const BUNDLED_PUBLISHERS_REVISION = 1;

/**
 * v0 placeholder: a deterministic dev pubkey derived from a known seed phrase, shipped so the
 * `addTestAlert` dev path works out of the box. replace with real chromatika-team pubkey before
 * public release. the matching privkey for this dev pubkey is generated by
 * `scripts/publish-alert.mjs` from `chromatika-dev-publisher-v0` seed; it's NOT a real key
 * and is fine to embed - anyone can sign dev alerts on their local install with it.
 */
export const PLACEHOLDER_DEV_PUBLISHER_PUBKEY_B64 = '+Qzgt7hrnGc94nPyvFFmQuv+EzRxCBvYsCN0XHHkWQA=';

export const BUNDLED_PUBLISHERS: ReadonlyArray<PublisherEntry> = Object.freeze([
  {
    pubkeyB64: PLACEHOLDER_DEV_PUBLISHER_PUBKEY_B64,
    label: 'chromatika dev publisher (placeholder)',
    addedAt: '2026-04-30',
  },
  // TODO: add the real kitty4d / chromatika-team pubkey here and remove the placeholder.
]);

export function isAllowedPublisher(pubkeyB64: string): boolean {
  return BUNDLED_PUBLISHERS.some((p) => p.pubkeyB64 === pubkeyB64);
}

export function publisherLabel(pubkeyB64: string): string | null {
  return BUNDLED_PUBLISHERS.find((p) => p.pubkeyB64 === pubkeyB64)?.label ?? null;
}
